---
- name: "Creates project directory"
  file:
    path: "{{ application_path }}"
    state: "directory"

- name: "Get release timestamp"
  command: date -u +%Y%m%d%H%M%S
  register: timestamp

- name: "Name release directory"
  command: echo "{{ application_path }}/releases/{{ timestamp.stdout }}"
  register: release_path

- name: "Make sure release folder exists remotely"
  file:
    path: "{{ release_path.stdout }}"
    state: "directory"
    mode: "0775"

- name: "Find poetry"
  local_action: "command which poetry"
  register: poetry

- name: "Build application"
  local_action: "command {{ poetry.stdout }} build"

- name: "Unpack distribution on server"
  unarchive:
    src: "{{ distribution_path }}"
    dest: "{{ release_path.stdout }}"
    extra_opts:
      - --strip-components=1

- name: "Finish deployment"
  file:
    state: "link"
    path: "{{ application_path }}/current"
    src: "{{ release_path.stdout }}"

- name: "Cleanup old releases"
  shell: "ls -dt {{ application_path }}/releases/* | tail -n +4 | xargs rm -rf"
